/**
 * One-time data preparation.
 *
 * Downloads public India district boundaries, simplifies them so the browser can
 * render the map quickly, and writes:
 *
 *   public/geo/india-states.json        state outlines (dissolved from districts)
 *   public/geo/districts/<slug>.json    district outlines for one state
 *   src/data/indiaLocations.js          state + district names for the dropdowns
 *
 * Run with:  npm run build:geo
 * The generated files are committed, so the app never downloads anything at runtime.
 */
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import mapshaper from 'mapshaper'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const BASE =
  'https://raw.githubusercontent.com/udit-001/india-maps-data/main/geojson'

const STATE_SLUGS = [
  'andaman-and-nicobar-islands',
  'andhra-pradesh',
  'arunachal-pradesh',
  'assam',
  'bihar',
  'chandigarh',
  'chhattisgarh',
  'delhi',
  'dnh-and-dd',
  'goa',
  'gujarat',
  'haryana',
  'himachal-pradesh',
  'jammu-and-kashmir',
  'jharkhand',
  'karnataka',
  'kerala',
  'ladakh',
  'lakshadweep',
  'madhya-pradesh',
  'maharashtra',
  'manipur',
  'meghalaya',
  'mizoram',
  'nagaland',
  'odisha',
  'puducherry',
  'punjab',
  'rajasthan',
  'sikkim',
  'tamil-nadu',
  'telangana',
  'tripura',
  'uttar-pradesh',
  'uttarakhand',
  'west-bengal',
]

async function download(url) {
  const res = await fetch(url)
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`)
  return Buffer.from(await res.arrayBuffer())
}

/** Runs mapshaper commands over an in-memory GeoJSON buffer. */
async function run(commands, inputBuffer) {
  const out = await mapshaper.applyCommands(
    `-i in.json ${commands} -o out.json`,
    { 'in.json': inputBuffer },
  )
  return JSON.parse(Buffer.from(out['out.json']).toString('utf8'))
}

/** Keeps only the properties the app actually reads, so files stay small. */
function slimFeatures(geo, keys) {
  return {
    type: 'FeatureCollection',
    features: geo.features.map((f) => {
      const properties = {}
      for (const key of keys) {
        if (f.properties?.[key] != null) properties[key] = f.properties[key]
      }
      return { type: 'Feature', properties, geometry: f.geometry }
    }),
  }
}

function kb(value) {
  return `${(Buffer.byteLength(JSON.stringify(value)) / 1024).toFixed(0)} KB`
}

async function main() {
  await mkdir(path.join(ROOT, 'public/geo/districts'), { recursive: true })
  await mkdir(path.join(ROOT, 'src/data'), { recursive: true })

  console.log('Downloading national district map...')
  const indiaRaw = await download(`${BASE}/india.geojson`)

  // Simplify while topology is still shared, then merge districts into states so
  // neighbouring states have no slivers or gaps between them.
  console.log('Building state outlines...')
  const states = slimFeatures(
    await run(
      '-simplify 3% keep-shapes -dissolve2 st_nm -clean',
      indiaRaw,
    ),
    ['st_nm'],
  )
  states.features.sort((a, b) =>
    a.properties.st_nm.localeCompare(b.properties.st_nm),
  )
  await writeFile(
    path.join(ROOT, 'public/geo/india-states.json'),
    JSON.stringify(states),
  )
  console.log(`  india-states.json  ${states.features.length} states  ${kb(states)}`)

  const index = []
  for (const slug of STATE_SLUGS) {
    const raw = await download(`${BASE}/states/${slug}.geojson`)
    const geo = slimFeatures(
      await run('-simplify 6% keep-shapes -clean', raw),
      ['district', 'st_nm'],
    )
    geo.features.sort((a, b) =>
      a.properties.district.localeCompare(b.properties.district),
    )

    const stateName = geo.features[0]?.properties?.st_nm
    if (!stateName) throw new Error(`No st_nm found in ${slug}`)

    await writeFile(
      path.join(ROOT, `public/geo/districts/${slug}.json`),
      JSON.stringify(geo),
    )

    index.push({
      name: stateName,
      slug,
      districts: geo.features.map((f) => f.properties.district),
    })
    console.log(
      `  ${slug.padEnd(30)} ${String(geo.features.length).padStart(3)} districts  ${kb(geo)}`,
    )
  }

  index.sort((a, b) => a.name.localeCompare(b.name))

  // Cross-check that every state on the map has a district file behind it.
  const mapped = new Set(index.map((s) => s.name))
  const missing = states.features
    .map((f) => f.properties.st_nm)
    .filter((name) => !mapped.has(name))
  if (missing.length) {
    throw new Error(`States on the map with no district data: ${missing.join(', ')}`)
  }

  const totalDistricts = index.reduce((sum, s) => sum + s.districts.length, 0)
  const file = `// AUTO-GENERATED by scripts/build-geo.mjs - do not edit by hand.
// ${index.length} states/UTs, ${totalDistricts} districts.

export const INDIA_STATES = ${JSON.stringify(index, null, 2)}

/** Slug used to load public/geo/districts/<slug>.json for a state name. */
export const STATE_SLUG_BY_NAME = Object.fromEntries(
  INDIA_STATES.map((state) => [state.name, state.slug]),
)

export const STATE_NAMES = INDIA_STATES.map((state) => state.name)

export function districtsOf(stateName) {
  return INDIA_STATES.find((state) => state.name === stateName)?.districts ?? []
}
`
  await writeFile(path.join(ROOT, 'src/data/indiaLocations.js'), file)

  console.log(
    `\nDone. ${index.length} states/UTs and ${totalDistricts} districts written.`,
  )
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
